# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:8000/")
    # 2 | setWindowSize | 1280x672 | 
    self.driver.set_window_size(1280, 672)
    # 3 | click | id=id_text | 
    self.driver.find_element(By.ID, "id_text").click()
    # 4 | type | id=id_text | hello
    self.driver.find_element(By.ID, "id_text").send_keys("hello")
    # 5 | click | name=submit | 
    self.driver.find_element(By.NAME, "submit").click()
    # 6 | click | linkText=Home | 
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    # 7 | click | css=.vsc-initialized | 
    self.driver.find_element(By.CSS_SELECTOR, ".vsc-initialized").click()
    # 8 | click | css=.vsc-initialized | 
    self.driver.find_element(By.CSS_SELECTOR, ".vsc-initialized").click()
  
