# Generated by Django 4.0.2 on 2022-06-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createDate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updateDate',
            new_name='updatedDate',
        ),
    ]
